# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proj.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='локаль')),
                ('index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='индекс')),
                ('robots', proj.db.fields.StripCharField(blank=True, choices=[(None, 'ALL'), ('index,nofollow', 'index, no follow'), ('noindex,noarchive,follow', 'no index, follow'), ('noindex,noarchive,nofollow', 'NONE')], max_length=32, null=True)),
                ('title', proj.db.fields.StripCharField(blank=True, max_length=255, null=True)),
                ('keywords', proj.db.fields.StripCharField(blank=True, max_length=255, null=True)),
                ('description', proj.db.fields.StripCharField(blank=True, max_length=255, null=True)),
                ('name', proj.db.fields.StripCharField(max_length=255, null=True, verbose_name='заголовок')),
                ('label', proj.db.fields.StripCharField(blank=True, max_length=80, null=True, verbose_name='пункт меню')),
                ('aliace', proj.db.fields.StripCharField(blank=True, max_length=1024, null=True)),
                ('slug', proj.db.fields.StripCharField(blank=True, db_index=True, max_length=1024, null=True, verbose_name='URI')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='в публикации')),
                ('published_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='старт')),
                ('archived', models.BooleanField(db_index=True, default=False, verbose_name='в архиве')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('owner', proj.db.fields.StripCharField(choices=[('ooo-ssk', 'ООО «ССК»'), ('ooo-ssk-proekt', 'ООО «ССК-Проект»')], db_index=True, default='ooo-ssk', max_length=128, verbose_name='владелец')),
                ('number', proj.db.fields.StripCharField(blank=True, max_length=128, null=True, verbose_name='номер')),
                ('provider', proj.db.fields.StripCharField(max_length=128, verbose_name='кем выдано')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='дата выдачи')),
                ('onset_date', models.DateField(blank=True, null=True, verbose_name='начало действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='окончание действия')),
                ('note', proj.db.fields.StripTextField(blank=True, null=True, verbose_name='примечания')),
                ('change_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='редактор')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'ordering': ('-locale', 'owner', 'index'),
                'db_table': 'cck_permit',
            },
        ),
        migrations.AlterUniqueTogether(
            name='permit',
            unique_together=set([('locale', 'owner', 'slug')]),
        ),
    ]
