# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import proj.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', proj.db.fields.StripCharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('description', proj.db.fields.StripTextField(blank=True, null=True, verbose_name='описание')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='активно')),
                ('index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='индекс')),
                ('public', models.BooleanField(db_index=True, default=False, verbose_name='публичный')),
                ('type', proj.db.fields.StripCharField(blank=True, max_length=32, null=True, verbose_name='тип')),
                ('name', proj.db.fields.StripCharField(db_index=True, default='', max_length=80, verbose_name='название')),
            ],
            options={
                'verbose_name_plural': 'альбомы',
                'ordering': ('-active', 'index'),
                'abstract': False,
                'verbose_name': 'альбом',
            },
        ),
        migrations.CreateModel(
            name='AlbomGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', proj.db.fields.StripCharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('description', proj.db.fields.StripTextField(blank=True, null=True, verbose_name='описание')),
                ('object_id', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='индекс')),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='proj_gallery.Albom', verbose_name='альбом')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'альбомы',
                'ordering': ('content_type', 'object_id', 'index'),
                'verbose_name': 'альбом',
            },
        ),
        migrations.CreateModel(
            name='AlbomThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', proj.db.fields.StripCharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('description', proj.db.fields.StripTextField(blank=True, null=True, verbose_name='описание')),
                ('alt', proj.db.fields.StripCharField(blank=True, max_length=255, null=True, verbose_name='alt')),
                ('index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='индекс')),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj_gallery.Albom', verbose_name='альбом')),
            ],
            options={
                'verbose_name_plural': 'изображения',
                'ordering': ('albom', 'index'),
                'abstract': False,
                'verbose_name': 'изображение',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', proj.db.fields.StripCharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('description', proj.db.fields.StripTextField(blank=True, null=True, verbose_name='описание')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='активно')),
                ('index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='индекс')),
                ('alt', proj.db.fields.StripCharField(blank=True, max_length=255, null=True, verbose_name='alt')),
                ('file', models.ImageField(blank=True, height_field='height', null=True, upload_to='', verbose_name='загрузить', width_field='width')),
                ('path', proj.db.fields.StripCharField(blank=True, max_length=64, null=True, verbose_name='путь к файлам')),
                ('type', proj.db.fields.StripCharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='тип')),
                ('name', proj.db.fields.StripCharField(db_index=True, max_length=128, null=True, verbose_name='название')),
            ],
            options={
                'verbose_name_plural': 'изображения',
                'ordering': ('-active', 'type', 'name'),
                'abstract': False,
                'verbose_name': 'изображение',
            },
        ),
        migrations.CreateModel(
            name='ImageGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', proj.db.fields.StripCharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('description', proj.db.fields.StripTextField(blank=True, null=True, verbose_name='описание')),
                ('alt', proj.db.fields.StripCharField(blank=True, max_length=255, null=True, verbose_name='alt')),
                ('index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='индекс')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='proj_gallery.Image', verbose_name='изображение')),
            ],
            options={
                'verbose_name_plural': 'изображения',
                'ordering': ('content_type', 'object_id', 'index'),
                'abstract': False,
                'verbose_name': 'изображение',
            },
        ),
        migrations.AddField(
            model_name='albomthrough',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='proj_gallery.Image', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='albom',
            name='image',
            field=models.ManyToManyField(related_name='_albom_image_+', through='proj_gallery.AlbomThrough', to='proj_gallery.Image', verbose_name='страницы'),
        ),
        migrations.AlterUniqueTogether(
            name='imagegeneric',
            unique_together=set([('content_type', 'object_id', 'image')]),
        ),
        migrations.AlterUniqueTogether(
            name='albomthrough',
            unique_together=set([('albom', 'image')]),
        ),
        migrations.AlterUniqueTogether(
            name='albomgeneric',
            unique_together=set([('content_type', 'object_id', 'albom')]),
        ),
    ]
