# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proj.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', proj.db.fields.StripCharField(db_index=True, max_length=128, verbose_name='имя')),
                ('email', proj.db.fields.StripCharField(db_index=True, max_length=128)),
                ('phone', proj.db.fields.StripCharField(blank=True, max_length=128, null=True, verbose_name='телефон')),
                ('subject', proj.db.fields.StripCharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='тема')),
                ('message', proj.db.fields.StripTextField(verbose_name='сообщение')),
                ('sent_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата')),
                ('state', models.CharField(blank=True, choices=[('0', 'Важное'), ('1', 'Прочитано'), ('2', 'Спам')], db_index=True, max_length=1, null=True, verbose_name='тип')),
                ('note', proj.db.fields.StripTextField(blank=True, null=True, verbose_name='примечание')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='агент')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.Site', verbose_name='сайт')),
            ],
            options={
                'verbose_name_plural': 'письма',
                'ordering': ('state', '-sent_date', 'site'),
                'db_table': 'proj_postbox',
                'verbose_name': 'письмо',
            },
        ),
    ]
